Metrics/LineLength:
  Max: 150

Style/EmptyLinesAroundClassBody:
  EnforcedStyle: false

Style/NumericPredicate:
  AutoCorrect: true

Style/AlignHash:
  Enabled: true

Style/HashSyntax:
  Enabled: true

Style/TrailingWhitespace:
  Enabled: true
